variables:
  AUTH: http://jenkins/job/chahra-be-node-js/buildWithParameters?token=&branch=$CI_COMMIT_REF_NAME

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
    - staging
  script:
    - 'curl -X post -L --user deploy:11cb6ad2404c0beef91cb6fe7a585072f3 ${AUTH}'
